# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_usercomplementar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomplementar',
            name='avatar',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
